version: '3'

services:
  db:
    image: 'mysql/mysql-server:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'password!23'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'forum'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - './volumes/database:/var/lib/mysql' 
    ports:
      - "3307:3306"
    networks:
      - forum
  
  admin-public:
    build: ./admin-public
    command: sh -c "npm update && npm run dev"
    volumes:
      - ./admin-public:/usr/src/app/admin-public
    environment:
      - NAME=admin-public
    ports:
      - "8080:5173"  
    networks:
      - forum
  
  forum-public:
    build: ./forum-public
    command: sh -c "npm update && npm run serve"
    volumes:
      - ./forum-public:/usr/src/app/forum-public
    environment:
      - NAME=forum-public
    ports:
      - "8081:8080"  
    networks:
      - forum
        
  dbapp:
    build: ./forum-db
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./forum-db:/usr/src/app/dbapp
    environment:
      - NAME=dbapp
    depends_on: 
      - db 
    networks:
      - forum

networks:
  forum:
    driver: bridge
